#!/bin/bash

log=$(norminette -R CheckForbiddenSourceHeader "$@")
awk '
	res_err = ""
BEGIN {
	res_ok = ""
}
/: Error!/ {
	fname=$1
	sub(/:$/, "", fname)
	next
}
/^Error:/ {
	line_num=$4; sub(/,/, "", line_num)
	col_num=$6; sub(/\):/, "", col_num)
	msg=""
	for (i=7; i<=NF; i++) {
		msg = msg $i " "
	}
	sub(/[ \t]+$/, "", msg)
	
	prefix = fname ":" line_num ":" col_num ":"
	pad = 33 - length(prefix)
	if (pad < 1) pad = 1
	res_err = res_err sprintf("%s%*s%s\n", prefix, pad, "", msg)
}
/: OK!/ {
	res_ok = res_ok $0 "\n"
}
END {
	print "\033[32m" res_ok "\033[0m"
	print "\033[31m" res_err "\033[0m"
}
' <<< "$log"